# Python releases to test
language: python
python:
  - "2.6"
  - "2.7"
  
# Django releases
env:
  - DJANGO_VERSION="django>=1.4,<1.5"
  - DJANGO_VERSION="django>=1.5,<1.6"
  - DJANGO_VERSION="django>=1.6,<1.7"
  - DJANGO_VERSION="django>=1.7,<1.8"
  
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION="django>=1.6,<1.7"
    - python: "2.6"
      env: DJANGO_VERSION="django>=1.7,<1.8"
        
# Package installation
install: 
  - pip install $DJANGO_VERSION --use-mirrors
  - pip install -r requirements-test.txt --use-mirrors
  
# Run the tests
script: coverage run --source emailmessagetemplates runtests.py emailmessagetemplates

# report coverage to coveralls.io
after_success: coveralls
