# Python releases to test
language: python
python:
  - "2.7"
  
# Django releases
env:
  - DJANGO_VERSION="django>=1.9,<1.10"
  - DJANGO_VERSION="django>=1.10,<1.11"
  - DJANGO_VERSION="django>=1.11,<1.12"
        
# Package installation
install: 
  - pip install $DJANGO_VERSION
  - pip install -r requirements-test.txt
  
# Run the tests
script: coverage run --source emailmessagetemplates runtests.py emailmessagetemplates

# report coverage to coveralls.io
after_success: coveralls
